import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireAuth } from '@/lib/auth-middleware'
import { calculateRecommendations } from '@/lib/recommendation'

// Submit quiz and get recommendation
export async function POST(request) {
    const { user, error, status } = await requireAuth(request)
    if (error) return NextResponse.json({ error }, { status })

    const { answers, totalQuestions } = await request.json()

    if (!answers || !Array.isArray(answers)) {
        return NextResponse.json({ error: 'Answers array required' }, { status: 400 })
    }

    // Calculate score and recommendations based on the raw answers
    const recommendations = calculateRecommendations(answers)
    const topField = recommendations[0]?.field || 'cs'
    const topFieldName = recommendations[0]?.fieldData?.name || topField

    // --- AI ANALYSIS GENERATION ---
    const NVIDIA_API_KEY = process.env.NVIDIA_API_KEY
    if (NVIDIA_API_KEY && answers.length > 0) {
        try {
            const history = answers.map((a, i) => `Q${i + 1}: ${a.questionText}\nAnswer: ${a.selectedOptionText}`).join('\n\n')
            
            const SYSTEM_PROMPT = `You are an expert career counselor. A high school student in Pakistan has just completed a career aptitude quiz.
Based on their answers, the system has determined their best career match is: ${topFieldName}.

Here is their quiz history:
${history}

Write a highly personalized, encouraging 1-2 paragraph explanation of exactly WHY this specific field is a perfect fit for them, referencing their specific answers directly. Do NOT use markdown asterisks or formatting, just write plain text paragraphs. Make it sound professional yet inspiring.`

            const res = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${NVIDIA_API_KEY}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    model: 'meta/llama-3.1-8b-instruct',
                    messages: [
                        { role: 'system', content: SYSTEM_PROMPT },
                        { role: 'user', content: 'Generate the personalized career analysis now.' },
                    ],
                    max_tokens: 500,
                    temperature: 0.7,
                }),
            })

            if (res.ok) {
                const data = await res.json()
                const aiExplanation = data.choices?.[0]?.message?.content?.trim()
                if (aiExplanation) {
                    recommendations[0].explanation = aiExplanation
                }
            } else {
                console.error('Nvidia AI API failed during analysis generation:', res.status)
            }
        } catch (err) {
            console.error('AI Analysis Generation Error:', err)
            // Fallback to the default explanation already generated by calculateRecommendations
        }
    }

    // Calculate a score (percentage)
    const score = recommendations[0]?.confidence || 0

    // Save quiz result
    const quizResult = await prisma.quizResult.create({
        data: {
            userId: user.id,
            score,
            totalQuestions: totalQuestions || answers.length,
            answers: answers,
            recommendedField: topField,
        },
    })

    // Save detailed recommendations
    const recommendation = await prisma.recommendation.create({
        data: {
            userId: user.id,
            fields: recommendations,
            quizResultId: quizResult.id,
        },
    })

    return NextResponse.json({
        quizResult,
        recommendations,
        recommendation,
    })
}

// GET user's quiz history
export async function GET(request) {
    const { user, error, status } = await requireAuth(request)
    if (error) return NextResponse.json({ error }, { status })

    const results = await prisma.quizResult.findMany({
        where: { userId: user.id },
        orderBy: { createdAt: 'desc' },
        take: 10,
    })

    return NextResponse.json({ results })
}
